### ISSUE TITLE
Thank you for WishList for coverage

### ISSUE THREAD

**Issue by mame** [grosser/ruby-coverage-talk#1]
Hello, I'm an author of coverage.so.  Unfortunately I missed your talk (I'll see the video later!), but some of my friends told me your coverage wishlist, so I took a glance at your slides.  I'd like to add my comments.

* "Oneshot usable for coverage calculations"

Sorry, I couldn't understand how it is more useful than [1, 0, nil].

* "Oneshot branches"

It looks natural and reasonable.  I didn't implement it just because I was unsure if it is really needed.  So, a patch is welcome :-)

* "Inherit coverage in forks"

`Coverage.start inherit_on_fork: true` looks great.  A patch is welcome too!

* "Coverage for default parameters" and "Coverage for logical operators"

I think that this is a request for branch coverage, and I agree.  One design issue is the format of the result.  Do you have any idea?

```
def foo(a=default, b=default2)
end

:branches=>{
  [:"a-in-foo"???, 0, what line+column of beginning??, what line+column of end??] => {
    [:"default-is-evaluated"???, 1, start line+column??, end line+column??] => 1,
    [:"default-is-skipped"???, 2, start line+column??, end line+column??] => 1,
  },
  [:"b-in-foo"???, ...
}
```

* "Path coverage"

I understand, but it would require much tougher work than other requests.  First we need to define what is path coverage in Ruby.

* "Turn on for loaded code"

It is difficult because of implementation limitation.  Some coverage hooks (for branch coverage) are inserted during bytecode compilation, so coverage measurement must be enabled before a target file is load.

However, "per request/controller coverage" may be already possible by using `Coverage.result` options.

```
def request
  Coverage.result stop: false, clear: true

  # .. handle request ...

  cov = Coverage.result stop: false, clear: true
  File.binwrite("coverage-per-request-#{ id }.dump", Marshal.dump(cov))
end
```

Does this work for you?

Anyway, thank you for playing with coverage.so.  If you have time at the 3rd day of RubyKaigi (i.e., tomorrow), will you have a chat with me somewhere?

**Comment by grosser** [comment]
- "Oneshot usable for coverage calculations"
atm it returns the covered line numbers, but from that it's not possible to tell the different between "uncovered code"(code without tests) and "uncoverable code" (else/end/comments)

 - "Coverage for default parameters" and "Coverage for logical operators"
I was thinking `param: {[:a, start of a, end of a] => 1, [:a, start of default, end of default] => 1}`

 - "Turn on for loaded code" ... yeah was kinda expecting that, no big deal, can work around this with oneshot :)

 - Path coverage: Agreed, was hoping you knew how this would work ... not that urgent since it's only needed for very small areas of code anyway 🤷‍♂ 

 - Meet: did not get notified because I was not watching the repo ... maybe we can meet next year in a "nice" place ;)
